### PR TITLE
Plotlyviz

### PR DESCRIPTION
**Pull request by empet**
Hi @sauln and @MLWave,

Here is my new PR on including Plotly visualization for kmapper graphs.

- I defined the  file `plotlyviz.py`, that only makes a few imports from `visuals`, and  did not perform any change in the  original kmapper files.

- In the folder `examples` I included a Jupyter notebook for `makecircles`, `cat`, `digits`, and `breast-cancer`,  as well as a pdf file for the Plotly figure representing the corresponding dataset.
At the first inspection it is recommended to read the notebooks in the order given above, because each one illustrates more plotting capabilities, compared with the previous.

- A notebook `Plotly-colorscale.ipynb` explains how we can convert matplotlib colormaps to Plotly colorscales, to color the graph nodes and the bars of histograms illustrating node distribution.

- In `README.md` are inserted details on how to install  `plotly`, `ipywidgets`,  and `python-igraph`.

### CODE REVIEW

**Comment by sauln** [comment]
I squashed all the commits with commit message 'first commit' into a single commit so this is easier to look at.

**Comment by sauln** [comment]
Hi @empet, 

Apologies for the delay.  Would you mind taking a look at the most recent changes I've made to the notebooks and code?  I think everything is working okay.  I added a function that wraps most of the code built up in the notebooks so that for users who aren't as familiar with plotly can build the visuals with just one function being called.

Let me know if it's okay, or please suggest changes.

Thank you,
Nathaniel

**Comment by empet** [comment]
Hi @sauln,
The Plotly-demo  is absolutely great. Nice work!!!

**Comment by sauln** [comment]
Hey @empet!  Thanks for all the work you put into making these visualizations.  I am very excited to incorporate these.  Sorry I have been moving slowly on this, but I think we're all ready to incorporate.  

Thank you again! 🍾

**Comment by deargle** [comment]
@empet I am reworking the kmapper.py and visuals.py to decouple it from jinja and to refactor the color value calculation to be more customizable. In doing so, I noticed that plotlyviz.py reimplements a lot of visuals.py. Is this because jinja and html are tied into both kmapper.py and visuals.py? If so, once jinja is decoupled, I suspect that plotlyviz.py could be refactored to cut out a lot of duplicated code and logic, to make maintenance easier. WIth my refactor, visuals.py does all preparatory work separate from any html rendering.

**Comment by deargle** [comment]
Specifically was looking at `get_mapper_graph` and the functions that it calls, such as `scomplex_to_graph`

**Pull request merged**
