### PR TITLE
Allow sparse matrix input to visuals._format_cluster_statistics

### PR DESCRIPTION
**Pull request by galtay**
Original code works for dense arrays but not sparse arrays. 

`np.std(X, axis=0)` 

This PR updates the code so that X can be either a dense or sparse array.

### CODE REVIEW

**Comment by sauln** [comment]
Sweet, thank you!  Could you please add a test similar to this one that shows it working with a sparse array? 
 https://github.com/scikit-tda/kepler-mapper/blob/4c52847c11333ce72afa47dbf8f04babe819dfb4/test/test_visuals.py#L206

**Comment by galtay** [comment]
hmmm, something is confusing me about the current test ... going to run a little experiment and check back in.

**Comment by galtay** [comment]
OK, I think I figured out my confusion by being explicit about the format of sparse matrices that are allowed. Some operations are not available for all format so I restricted to csc and csr (compatible with sklearn outputs).

**Comment by galtay** [comment]
@sauln not sure if the codecov checks are my fault, but pretty sure the tests are OK now.

**Comment by sauln** [comment]
Looks great! thank you!

**Comment by galtay** [comment]
thanks sauln, great project!

**Pull request merged**
