### PR TITLE
large update iteration of .visualize

### PR DESCRIPTION
**Pull request by MLWave**

### CODE REVIEW

**Comment by sauln** [comment]
These updates look awesome! Can't wait to play around with them. 

(it looks like you're using travis for tests. Have you been able to run tests locally? if not, pip install pytest, then run pytest from the command line)

**Comment by MLWave** [comment]
Thanks, am now able to run tests locally. Will keep fixing some PEP8 bugs, and make accept the old parameters.

Not sure yet how to fix Codecov checks.

**Comment by sauln** [comment]
Great!  It's probably not an issue to ignore all the E501 pep8 violations.  There are so many of those it'll take forever.

The only way to fix the codecov is to write more tests. Most basically, if you add a few tests that exercise some of the different new parameters and new control flow, the coverage should go up. I can help with this a bit tomorrow.

**Comment by MLWave** [comment]
@pep8speaks ola!

**Pull request closed without merging**
